wrappid/core

ATTRIBUTIONS.md, attributions.json, package.json, scripts/attributions.gen.js, scripts/contribution.gen.js
generate a attributions.gen.js file and install a licence-checker package
ref: #76
=> docs: :memo: generate and add ATTRIBUTION file in core

package-lock.json, package.json, package/CoreApp.js, package/layout/WrappidGuest.layout.js, package/package-lock.json, package/package.json, package/theme/ThemeSelector.js
add missing keys, author, license, in package.json
Ref: https://github.com/wrappid/core/issues/88
=> docs(config): 📝 add missing keys in package.json

ATTRIBUTIONS.md, scripts/attributions.gen.js
correct the details of name, version in the table
ref: #76
=> docs: :memo: correct details in the table

package/index.js
CoreRoutesContext was not imported in Core index.js file.
ref: #85
=> fix(core): :bug: import the missing component CoreRoutesContext

package/components/dataDisplay/CoreAvatarGroup.js
fixed prop table of spacing and varient
=> bugfix: fixed valid props table content of CoreAvatarGroup

package/styles/LargeCoreStyles.js, package/styles/MediumCoreStyles.js
change in the size of authWrapper in MediumCoreStyles and LargeCoreStyles file.
ref: #18
pr ref: #118
=> fix: :bug: change in the size of authWrapper

package/components/dataDisplay/CoreTypography.js, package/components/dataDisplay/CoreTypographyBody2.js
gutterBottom default value changed to false in coreTypography
ref #121
=> fix: :bug: gutterBottom default value changed to false.

package-lock.json, package.json, package/package-lock.json
version update for package release and publish
Ref #no-issue
=> ci(global): :heavy_plus_sign: version update for release

package/components/surfaces/CoreRightDrawer.js
add valid and invalid props in CoreRightDrawer.js
ref: #127
=> fix: :bug: add valid and invalid props

package/styles/CoreClasses.js, package/styles/DefaultCoreStyles.js, package/styles/LargeCoreStyles.js, package/styles/MediumCoreStyles.js, package/styles/SmallCoreStyles.js, package/styles/XLargeCoreStyles.js
Had remove 'Auth' style object from CoreClasses.js and it will be shifted to ModuleClasses.js of auth-module.
ref: #133
=> fix: :bug: removed Auth object from CoreClases.js

package/theme/CoreThemeProvider.js, package/theme/ThemeSelector.js
theme related fixes for rxefy app
ref: #91
=> theme related fixes

package/components/surfaces/CoreDrawer.js, package/utils/menuUtil.js
left menu openCollapse not working issue resolved in core package
ref: #103
=> fix: :bug: left menu openCollapse not working issue resolved

package/components/WrappidComponent.js, package/development/DevelopmentInfo.js, package/layout/BlankLayout.js, package/layout/PageContainer.js, package/layout/WrappidDefault.layout.js, package/layout/core/LayoutManager.js, package/layout/page/BlankLayoutPage.js, package/layout/page/FixedHeaderFooterLayoutPage.js, package/layout/page/FixedHeaderLayoutPage.js
enhancement: layout manager working on
=> enhancement: layout manager working

package/CoreRoutes.js, package/development/DevelopmentInfo.js, package/layout/PageContainer.js, package/layout/core/CoreLayoutPlaceholder.js, package/layout/core/LayoutManager.js, package/registry/ComponentsRegistry.js, package/registry/LayoutComponentsRegistry.js, package/utils/jsonUtils.js
route and layout related issue resolved in core package
ref: #130
=> route and layout related issue resolved

package/styles/CoreClasses.js
remove auth related styles from CoreClasses.js
Ref: #156
=> fix: :bug: remove auth related styles from CoreClasses

package/index.js, package/layout/LayoutViewer.js
create a LayoutViewer component  to view layouts
ref: #130
=> feat(core): :sparkles: create a LayoutViewer component

package/components/layouts/_system/FixedFooterLayout.js, package/components/layouts/_system/FixedHeaderFooterLayout.js, package/components/layouts/_system/FixedHeaderLayout.js, package/components/layouts/_system/FooterLayout.js, package/components/layouts/_system/LeftDrawerLayout.js, package/components/layouts/_system/LeftRightDrawerLayout.js, package/components/layouts/_system/RightDrawerLayout.js, package/components/layouts/_system/ThreeColumnLayout.js, package/components/layouts/_system/TwoColumnLayout.js, package/layout/LayoutViewer.js, package/styles/CoreClasses.js, package/styles/DefaultCoreStyles.js
add layouts aspect ration tabs  in LayoutViewer
=> Wrpd enhancement 130 add layouts aspect ration tabs 

package/components/feedback/CoreNetworkStatus.js
import issue resolved in index js of core for NetworkStatus
ref: #142
=> enhancement: CoreNetworkStatus implementation

package/components/dataDisplay/CoreImage.js
Add sanitize function to CoreImage.
=> bugfix: add sanitize function to CoreImage

package/components/utils/CoreNetworkStatus.js
error: Cannot read properties of null (reading 'scrollTop')
=> error when the network goes offline resolved

package/utils/componentUtil.js
add height and width in validProps arrayin ComponenetsUtils.js
ref: #184
=> feat(core): :sparkles: add height and width in validProps

package/CoreApp.js, package/CoreAppStrictWrapper.js, package/CoreRoutes.js, package/components/layouts/_system/AppContainerLayout.js, package/components/layouts/_system/BlankLayout.js, package/index.js, package/layout/PageContainer.js, package/middleware/coreTokenProvider.js, package/registry/ComponentsRegistry.js, package/store/action/appActions.js
1.  CoreRoutes API calls multiple time
2.  activate StrictMode in dev mode only
3.  Authentication related changes
4.  AppContainerLayout working
=> enhancement: delivery oriented fix

package/components/navigation/Logout.js, package/registry/ComponentsRegistry.js
logout added in component registry
Ref #183
=> fix(core): :zap: logout added in component registry

package/components/surfaces/CoreAppBar.js, package/components/surfaces/DefaultAppBarContent.js
Initial CoreAppBar related changes were pushed to issue ref: #142 .
the modifications regarding CoreAppBar will continue on issue ref: #190 .
=> bugfix: CoreAppBar related modifications

package/components/dataDisplay/CoreEmailOrPhoneLink.js, package/components/dataDisplay/CoreTimer.js, package/components/dataDisplay/dataTable/CoreDataTableRow.js, package/components/dataDisplay/dataTable/CoreDataTableToolbar.js, package/components/dataDisplay/dataTable/CoreTableAction.js, package/components/dataDisplay/dataTable/FilterData.js, package/components/inputs/CoreButton.js, package/components/inputs/CoreIconButton.js, package/components/inputs/CoreResponsiveButton.js, package/components/inputs/forms/CoreFieldButton.js, package/components/inputs/forms/CoreForm.js, package/components/inputs/forms/CoreFormHeaderActions.js, package/components/inputs/forms/CoreFormInputs.js, package/components/surfaces/CoreCard.js, package/components/surfaces/CoreDrawer.js, package/components/utils/CoreProfilePopOver.js, package/theme/ThemeSelector.js, package/utils/formUtils.js
correct 'OnClick' to 'onClick' props
ref: #183
=> refactor(core): :recycle: correct 'OnClick' to 'onClick' props

package/styles/DefaultCoreStyles.js, package/styles/MediumCoreStyles.js, package/styles/SmallCoreStyles.js
core appbar margin-top bug fixed,
Login pages to dashboard login not working (splash component navigation problem)
Logout navigation not working
Left drawer click not working (valid props missing toggleDrawer in coreDrawer)
profile popover navigation links (view profile, settings) not working. (route registry from context coming empty in CoreProfilePopOver component )
ref: #183
=> fix(core): :bug: core appbar margin-top bug fixed

package/theme/CoreThemeProvider.js
theme undfined bugfixed
ref:#183
=> fix(core): :bug: theme undfined bugfixed

package/CoreRoutes.js, package/components/PageLoader.js, package/components/layouts/CoreAppDiv.js, package/components/layouts/_system/AppContainerLayout.js, package/components/navigation/Logout.js, package/components/navigation/SplashComponent.js, package/components/surfaces/CoreDrawer.js, package/components/surfaces/CoreFooter.js, package/components/utils/CoreFade.js, package/components/utils/CoreProfilePopOver.js, package/components/utils/CoreTermsPrivacyLink.js, package/development/DevelopmentInfo.js, package/layout/PageContainer.js, package/route/CoreRoutesProvider.js, package/theme/CoreThemeProvider.js
enhancement: theme and auth specific code handled
#183
=> enhancement: theme and auth specific code handled

package/package-lock.json, package/package.json
added peerDependenciesMeta to resolve react peerDependencies issues with version config
ref: #214
=> fix(core): :bug: added peerDependenciesMeta to resolve react peerDependencies issues

package/service/AppService.js
axios request method uppercase
Ref: #216
=> fix: :bug: axios request method uppercase

package/components/inputs/CoreButton.js, package/components/inputs/CoreResponsiveButton.js, package/components/inputs/CoreTextField.js, package/components/inputs/forms/CoreForm.js
CoreButton valid props added title, titlePlacement and on delete cancel button enable
Ref: #224
=> fix: :bug: CoreButton valid props added title, titlePlacement

package/theme/CoreThemeProvider.js
fix loading default theme
Ref: #224
=> fix(core): :bug: fix loading default theme

package/components/inputs/CoreAsyncSelect.js, package/components/navigation/CoreTabHead.js, package/index.js
valid props add to CoreTabHead
Ref: #224
=> bugs & enhancement: tab fix and CoreFunctionsRegistryContext exported

package/components/inputs/CoreImagePicker.js
change CoreImagePicker default image to a more suitable image
ref: #236
=> feat(utils): :lipstick: change CoreImagePicker default image

package/components/inputs/CoreOtpInput.js
Send service name to request body
Ref: #242
=> feat(core): :zap: coreOtpInput service name

package/components/dataDisplay/CoreTypographyBody1.js, package/components/dataDisplay/CoreTypographyBody2.js, package/components/dataDisplay/CoreTypographyCaption.js, package/components/dataDisplay/CoreTypographyOverline.js, package/components/dataDisplay/CoreTypographySubtitle1.js, package/components/dataDisplay/CoreTypographySubtitle2.js
cursor pointer added to see more and see less in some of the CoreTypography related components where hideSeeMore is false
Ref: #246
=> perf(core): :adhesive_bandage: cursor point added to see more and seeless

package/components/inputs/CoreTextarea.js
coreInput valid props add valid props in CoreTextarea
Ref: #248
=> fix(global): :bug: add valid props in CoreTextarea

package/components/inputs/CoreCheckbox.js, package/components/inputs/forms/CoreSpecificForm.js
fomik valid props add to CoreCheckbox
Ref: #248
=> fix(global): :bug: valid props add to CoreCheckbox

package/components/inputs/forms/CoreSpecificForm.js
remove unnecessary encodingURIcomponent function
Ref: #251
=> fix(core): :bug: remove unnecessary encodingURIcomponent function

package/components/inputs/forms/CoreForm.js, package/components/layouts/_system/AppContainerLayout.js, package/layout/PageContainer.js, package/middleware/axiosInterceptor.js, package/service/AppService.js, package/store/action/appActions.js, package/utils/appUtils.js, package/utils/formUtils.js
update access token by refresh token
Ref: #253
=> feat(global): :sparkles: update access token by refresh token

package/components/dataDisplay/CoreTimer.js, package/layout/PageContainer.js, package/store/reducers/themeReducer.js, package/theme/CoreThemeProvider.js, package/utils/jsonUtils.js
page theme merge with default theme
Ref: #255
=> feat(global): :sparkles: page theme merge with default theme

package/components/dataDisplay/CoreEmailOrPhoneLink.js, package/components/dataDisplay/CorePhoneLink.js, package/components/layouts/CoreSection.js
=> bugfix: DataDisplay components enhancement

package/utils/componentMap.js
core json input changed to core json editor
Ref #260
=> fix(core): :bug: core json input changed to core json editor

package/components/inputs/forms/CoreForm.js
coreForm read api not working with local formJson
Ref: #266
=> fix(core): :bug: coreForm read api not working with local formJson
